eval "$(starship init zsh)"

# opencode
export PATH=/home/matthew/.opencode/bin:$PATH

# Rust包管理环境工具
. "$HOME/.cargo/env"

# ics-pa实验
export AM_HOME=/home/matthew/programming/ics-pa/abstract-machine
export NAVY_HOME=/home/matthew/programming/ics-pa/navy-apps

# i3wn 打开vscode
echo "alias code='code --ozone-platform=x11'" >> ~/.zshrc
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
alias code='code --ozone-platform=x11'
