[colors.primary]
background = "#282C34"
foreground = "#C3C7D1"

[colors.cursor]
text = "#282C34"
cursor = "#C3C7D1"

[colors.normal]
black   = "#282C34"
red     = "#ED254E"
green   = "#71F79F"
yellow  = "#F9DC5C"
blue    = "#7CB7FF"
magenta = "#C74DED"
cyan    = "#00C1E4"
white   = "#DCDFE4"

[colors.bright]
black   = "#282C34"
red     = "#ED254E"
green   = "#71F79F"
yellow  = "#F9DC5C"
blue    = "#7CB7FF"
magenta = "#C74DED"
cyan    = "#00C1E4"
white   = "#DCDFE4"

[font]
size = 10

[font.normal]
family = "FiraCode Nerd Font Mono"

[cursor]
style = { shape = "Block" }

[window]
dimensions = { columns = 85, lines = 20 }
