[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "nvim", for = "unix" },
]

[open]
edit = "nvim"

[preview]
max_width = 1000
max_height = 1000
image_quality = 90
image_filter = "lanczos3"
