set -g status on
set -g status-bg blue
set -g status-fg white

# 窗口标签居中
set -g status-justify absolute-centre


set -g status-left "#S "
set -g status-right "%Y-%m-%d %H:%M"
set -g status-position top
